---
- name: Cowin Playbook
  hosts: localhost
  gather_facts: false
  vars: 
    cowin_host: cdn-api.co-vin.in
  # vars_files:
  #   - var.yml

  tasks:
  - name: Geting the name of State List
    uri:
      url: "https://{{cowin_host}}/api/v2/admin/location/states"
    register: stateoutput
    tags:
    - statelists

  - name: printing state output
    debug:
      var: stateoutput.json.states
    tags:
    - statelists